export const LOGIN_ACTION = 'login_action'
export const INIT_SESSION = 'init_session'
export const MOVIE_LIST = 'movie_list'
export const CLOSE_MENU = 'close_menu'
export const INIT_FAVORITE = 'init_favorite'
export const SAVE_RATING = 'save_rating'
export const SAVE_USER = 'save_user'
